# theme: jekyll-theme-minimal
remote_theme: pages-themes/time-machine@v0.2.0
plugins     :
- jekyll-remote-theme
title       : e4cTraining
name        : Robert Kuropkat
description : Training modules for e4c as completed by Robert Kuropkat
repository  : "robert-kuropkat/e4cTraining"
timezone    : America/New_York