# theme: jekyll-theme-minimal
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
title: e4cTraining
tagline: JavaScript Tutorial
description: Bookmark this to keep an eye on my project updates!