import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from './components/Header';

const poppins = Poppins(
  {
      weight  : ['400', '700']
    , subsets : ['latin']
  }
);
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title       : "Doers of Stuff NextJS Training"
  , description : "Generated by create next app, then mucked up by me..."
  , keywords    : 'training, nextjs'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
